/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as ProjectsUpcomingRouteImport } from './routes/projects/upcoming'
import { Route as ProjectsOngoingRouteImport } from './routes/projects/ongoing'
import { Route as ProjectsCompletedRouteImport } from './routes/projects/completed'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsUpcomingRoute = ProjectsUpcomingRouteImport.update({
  id: '/projects/upcoming',
  path: '/projects/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsOngoingRoute = ProjectsOngoingRouteImport.update({
  id: '/projects/ongoing',
  path: '/projects/ongoing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCompletedRoute = ProjectsCompletedRouteImport.update({
  id: '/projects/completed',
  path: '/projects/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/projects/ongoing': typeof ProjectsOngoingRoute
  '/projects/upcoming': typeof ProjectsUpcomingRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/projects/ongoing': typeof ProjectsOngoingRoute
  '/projects/upcoming': typeof ProjectsUpcomingRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/projects/ongoing': typeof ProjectsOngoingRoute
  '/projects/upcoming': typeof ProjectsUpcomingRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$projectId'
    | '/projects/completed'
    | '/projects/ongoing'
    | '/projects/upcoming'
    | '/properties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/$projectId'
    | '/projects/completed'
    | '/projects/ongoing'
    | '/projects/upcoming'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/projects/$projectId'
    | '/projects/completed'
    | '/projects/ongoing'
    | '/projects/upcoming'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsCompletedRoute: typeof ProjectsCompletedRoute
  ProjectsOngoingRoute: typeof ProjectsOngoingRoute
  ProjectsUpcomingRoute: typeof ProjectsUpcomingRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/upcoming': {
      id: '/projects/upcoming'
      path: '/projects/upcoming'
      fullPath: '/projects/upcoming'
      preLoaderRoute: typeof ProjectsUpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/ongoing': {
      id: '/projects/ongoing'
      path: '/projects/ongoing'
      fullPath: '/projects/ongoing'
      preLoaderRoute: typeof ProjectsOngoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/completed': {
      id: '/projects/completed'
      path: '/projects/completed'
      fullPath: '/projects/completed'
      preLoaderRoute: typeof ProjectsCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsCompletedRoute: ProjectsCompletedRoute,
  ProjectsOngoingRoute: ProjectsOngoingRoute,
  ProjectsUpcomingRoute: ProjectsUpcomingRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
